-- AUD-001 foundation / migration 002
-- Tenant and location roots. UUIDs are generated by the application.

CREATE TYPE tenant_status AS ENUM ('ACTIVE', 'SUSPENDED', 'ARCHIVED');
CREATE TYPE location_status AS ENUM ('ACTIVE', 'INACTIVE', 'ARCHIVED');

CREATE TABLE tenants (
  id UUID PRIMARY KEY,
  name VARCHAR NOT NULL,
  status tenant_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE locations (
  id UUID PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
  name VARCHAR NOT NULL,
  address TEXT,
  phone TEXT,
  status location_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL DEFAULT 1,
  CONSTRAINT locations_tenant_name_key UNIQUE (tenant_id, name)
);

CREATE INDEX locations_tenant_id_idx ON locations (tenant_id, id);
CREATE INDEX locations_tenant_status_idx ON locations (tenant_id, status);
