-- AUD-001 foundation / migration 003
-- Identity and tenant membership roots. UUIDs are generated by the application.

CREATE TYPE identity_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DISABLED');
CREATE TYPE membership_status AS ENUM ('ACTIVE', 'SUSPENDED', 'REVOKED');

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email TEXT,
  phone TEXT,
  status identity_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE memberships (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  tenant_id UUID NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
  role TEXT NOT NULL,
  status membership_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT memberships_user_tenant_key UNIQUE (user_id, tenant_id)
);
